// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"Community_Basic","status":true,"description":"基本的なパラメーターを設定するプラグインです。","parameters":{"cacheLimit":"10","screenWidth":"430","screenHeight":"710","changeWindowWidthTo":"","changeWindowHeightTo":"","renderingMode":"canvas","alwaysDash":"false","textSpeed":"1","autoSaveFileId":"0","errorMessage":"エラーが発生しました。ゲームの作者にご連絡ください。","showErrorDetail":"false","enableProgressBar":"false","maxRenderingFps":"0"}},
{"name":"111_InputForm","status":true,"description":"フォーム作って文字入力","parameters":{}},
{"name":"DTextPicture","status":true,"description":"動的文字列ピクチャ生成プラグイン","parameters":{}},
{"name":"DataCacheBlocker","status":true,"description":"キャッシュを阻止します。（dataフォルダのみ）","parameters":{}},
{"name":"TMAutoNewGame","status":true,"description":"起動時に自動ではじめからゲームを開始します。\r\nWeb用ミニゲームなど、タイトルが不要な場合に使えます。","parameters":{"autoNewGame":"1","allwaysOnTop":"0","autoDevTool":"0"}},
{"name":"HyperLink","status":true,"description":"ゲーム中に外部ページへのリンクを貼ります。","parameters":{"description":"Webサイトへのリンク"}},
{"name":"EasingPicture","status":true,"description":"ピクチャーの移動パターンを増やします。","parameters":{}},
{"name":"TimeEvent","status":true,"description":"時間の経過に応じてイベントを起こします。","parameters":{}},
{"name":"OggOnly","status":true,"description":"音声ファイルの再生にoggファイルのみを使用します。","parameters":{"deleteM4a":"false"}},
{"name":"KNH_CharacterShadow","status":true,"description":"キャラクターに影をつけるプラグイン","parameters":{"影画像":"Shadow3"}},
{"name":"stbvorbis","status":true,"description":"","parameters":{}},
{"name":"stbvorbis_asm","status":true,"description":"","parameters":{}},
{"name":"EasingPicture","status":true,"description":"ピクチャーの移動パターンを増やします。","parameters":{}},
{"name":"ServerTime","status":true,"description":"サーバータイムを取得します。","parameters":{}},
{"name":"PictureCallCommon","status":true,"description":"ピクチャのボタン化プラグイン","parameters":{"透明色を考慮":"true","ピクチャ番号の変数番号":"0","ポインタX座標の変数番号":"3","ポインタY座標の変数番号":"4","タッチ操作抑制":"false","戦闘中常にコモン実行":"false","無効スイッチ":"0"}},
{"name":"PluginCommandBook","status":true,"description":"プラグインコマンド集","parameters":{"制御文字の拡張":"はい","スクリプトに制御文字適用":"いいえ"}},
{"name":"ChangeMapTouchPolicy","status":true,"description":"マップタッチ仕様変更プラグイン","parameters":{"initPolicyLevel":"1","invalidForceDash":"false"}},
{"name":"EventNoLock","status":true,"description":"イベントロック無効化プラグイン","parameters":{}},
{"name":"PictureAnimation","status":true,"description":"ピクチャのアニメーションプラグイン","parameters":{"最初のセルに戻る":"false"}},
{"name":"EventReSpawn","status":true,"description":"イベント動的生成プラグイン","parameters":{"keepSelfSwitch":"false","tryRandomCount":"1000","CertainSpawnSwitch":"0"}},
{"name":"MKR_PlayerMoveForbid","status":true,"description":"(v1.0.5) プレイヤー移動禁止プラグイン","parameters":{"Default_Move_Flag":"22","Default_Menu_Flag":"false","Enter Flag":"false"}},
{"name":"PictureVariableSetting","status":true,"description":"ピクチャ関連のイベント機能拡張プラグイン","parameters":{"初期値":"OFF","ピクチャ表示最大数":""}},
{"name":"OnlineAvatar","status":true,"description":"Firebaseを使ってプレイヤーをオンライン同期します。","parameters":{"apiKey":"AIzaSyDT0fTCJPCSeEjCasW5abFdRG17gLP5rTE","authDomain":"tenseiyuusya.firebaseapp.com","databaseURL":"https://tenseiyuusya.firebaseio.com","avatarEvent":"1","syncSwitchStart":"200","syncSwitchEnd":"300","syncVariableStart":"200","syncVariableEnd":"500"}},
{"name":"TMBitmapEx","status":true,"description":"角丸の矩形や星を描画する機能を追加します。\n各種ゲージの形状を角丸矩形に自動変更する機能もあります。","parameters":{"gaugeHeight":"18","gaugeReduction":"2","cornerRadius":"6","minGaugeRate":"1.5"}},
{"name":"TMNamePop","status":true,"description":"イベントの頭上に文字列を表示する機能を追加します。","parameters":{"backOpacity":"250","fontSize":"18","fontOutlineWidth":"1","fontOutlineColor":"rgba(250, 250, 250, 0.5)","width":"160","useRoundRect":"1","roundRectRadius":"6"}}
];
